### ISSUE TITLE
Error when trying to compile latest version of img4tool with mingw32

### ISSUE THREAD

**Issue by iFred09** [tihmstar/img4tool#2]
Hello,

When I try to compile img4tool for windows with MinGW32 it don't work.
In MacOS and Linux it's fine.
Anyone can help ?

Thank's.
![img4tool](https://cloud.githubusercontent.com/assets/22419166/24331412/2baa9998-1234-11e7-89cf-19726dc0acc4.png)

**Comment by iFred09** [comment]
Any help ? It's the same with the last img4tool version.

**Comment by king4q** [comment]
@iFred09 would you tell me how you compile this and with what tools and what commands you use I would like to try myself and see if I can use it to convert my ApTicket.der to a blob because I got a replacement iPod and it was on 10.2 but it was way after the signing cutoff and I have the ApTicket.der from the /System/Libray/Caches/apticket.der and I want to convert it to a working blob for Restore in case of a bad tweak or something happens

**Comment by vladut123** [comment]
how to compile img4tool

**Comment by vladut123** [comment]
how to compile img4tool

**Comment by vladut123** [comment]
iFred09 help me how to compile futurerestore please

**Comment by s0uthwest** [comment]
Compile with OpenSSL.
