### ISSUE TITLE
The latest build is not compatible with x86 OSes (Win7x86)

### ISSUE THREAD

**Issue by mrdc** [tihmstar/img4tool#3]
Hello,

Unfortunately, the latest build is not compatible with x86 OS (Win7x86).

**Comment by tihmstar** [comment]
This is correct. The buildsystem i set up only creates binaries for 64bit Windows systems (which was painful enough already). I won't be creating automated builds for 32bit anymore, since there is stuff which could break if compilers handle stuff incorrectly and break basic assumtions about integer sizes. 
The code as it is should work on 32bit systems if compiled correctly (note 64bit integers are still required but they exist even in 32bit systems), so if you really need this for 32bit you can compile yourself.
